### PR TITLE
A lot of cleanup and refactoring

### PR DESCRIPTION
**Pull request by kevmoo**
See individual commits for all the fun details

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/dump-info-visualizer/33)

### CODE REVIEW

**Comment by kevmoo** [comment]
@jakemac53 if you're bored: https://reviewable.io/reviews/dart-lang/dump-info-visualizer/33

**Comment by jakemac53** [comment]
Review status: 0 of 18 files reviewed, 7 unresolved discussions, all commit checks successful.

---

<sup>**[lib/src/diff_view.dart, line 26 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmoUMyLPjrXqjYAMzE)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L26)):</sup>
I don't think you need the explicit cast here and below, but I could be wrong.

---

<sup>**[lib/src/diff_view.dart, line 36 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-Jpmp0h38l1EKoCFBg7X)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L36)):</sup>
you could probably use the => syntax here, and below

---

<sup>**[lib/src/diff_view.dart, line 54 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmpA506Wi6whlIB7Ty)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L54)):</sup>
I would make this if and the next one single line statements, but its up to you. Same thing applies elsewhere.

---

<sup>**[lib/src/diff_view.dart, line 93 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmpeUzhD-8ldukqwIf)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L93)):</sup>
Any reason for the explicit type here? I would tend to just pass JSON.decode directly to the fromJson call.

---

<sup>**[lib/src/program_info_view.dart, line 41 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmtcpbnbLlaoKMrfNt)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/program_info_view.dart#L41)):</sup>
imo: '${_model.size} bytes'

---

<sup>**[lib/src/program_info_view.dart, line 56 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmsqCiUKa8ILa5kFgj)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/program_info_view.dart#L56)):</sup>
shouldn't need an explicit type here

---

<sup>**[lib/src/program_info_view.html, line 12 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmtuYXpT1NU3Xljwl_)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/program_info_view.html#L12)):</sup>
The polymer way of doing things would be to use a template repeat here instead of doing a bunch of dom manip manually. Up to you though and this fits more with the current style. See https://github.com/dart-lang/polymer-dart-patterns/blob/8a12421c1b1c91816b42fcce7853d53dc8956b9b/web/control_flow/using_template_repeat_with_a_table_row_or_an_option/my_element.html for how to use template repeat with tables.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33)

**Comment by jakemac53** [comment]
Review status: 17 of 18 files reviewed, 7 unresolved discussions, all commit checks successful.
Reviewed files:
- lib/src/async.dart @ r1
- lib/src/dependency_view.dart @ r1
- lib/src/diff_alg.dart @ r1
- lib/src/diff_view.dart @ r1
- lib/src/hierarchy_view.dart @ r1
- lib/src/info_helper.dart @ r1
- lib/src/program_info_view.dart @ r1
- lib/src/program_info_view.html @ r1
- lib/src/util.dart @ r1
- lib/src/view_version.dart @ r1
- pubspec.yaml @ r1
- test/diff_test.dart @ r1
- test/info_helper_test.dart @ r1
- test/sample.info.json @ r1
- test/streams_test.dart @ r1
- web/index.html @ r1
- web/viewer.dart @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33)

**Comment by jakemac53** [comment]
lgtm

---

Review status: 17 of 18 files reviewed, 7 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33)

**Comment by jakemac53** [comment]
Review status: all files reviewed, 7 unresolved discussions, all commit checks successful.
Reviewed files:
- lib/dump_viz.dart @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33)

**Comment by kevmoo** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[lib/src/diff_view.dart, line 26 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmoUMyLPjrXqjYAMzE)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L26)):</sup>
I'm doing this to ensure a run-time exception (outside checked mode) if the type changes. Just being paranoid.

---

<sup>**[lib/src/diff_view.dart, line 36 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-Jpmp0h38l1EKoCFBg7X)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L36)):</sup>
I'm weird. I only like using `=>` if I'm getting values. I want it to be clear that I'm not relying on the return value.

---

<sup>**[lib/src/diff_view.dart, line 54 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmpA506Wi6whlIB7Ty)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/diff_view.dart#L54)):</sup>
Again, I'm perhaps annoying. I find it more clear to not hunt for calls in one-line if statements.

---

<sup>**[lib/src/program_info_view.html, line 12 \[r1\]](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33#-JpmtuYXpT1NU3Xljwl_)** ([raw file](https://github.com/dart-lang/dump-info-visualizer/blob/1efc5466c685c1fac12518305775d0c3cb6fe735/lib/src/program_info_view.html#L12)):</sup>
Understood. This was a naive refactoring of the existing code. I'm hoping to get more "polymer-ish" later.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33)

**Comment by kevmoo** [comment]
Thanks for the feedback. Just pushed a clean-up commit on top of the pull request.

PTAL

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/dump-info-visualizer/33)

**Pull request merged**
